// indexer.ts — regenerate /specs/_index.md from parsed specs (SPEC-911 T4)

import type { ParsedSpec, SpecFrontmatter } from './parser.ts';

/**
 * Build the markdown content for `_index.md`.
 * Groups: META first, then by layer (alphabetical numeric prefix).
 */
export function buildIndex(all: ParsedSpec[]): string {
  const sorted = [...all].sort(compareSpecs);

  const lines: string[] = [];
  lines.push('# Spec Index');
  lines.push('');
  lines.push('> Auto-regenerated by `nimbus spec index`. Edit source `.spec.md` files, not this.');
  lines.push(`> Last generated: ${today()}`);
  lines.push('');

  // META section
  const metas = sorted.filter((s) => s.frontmatter.id.startsWith('META-'));
  if (metas.length > 0) {
    lines.push('## Meta Specs');
    lines.push('');
    lines.push('| ID | Title | Status | Updated |');
    lines.push('|----|-------|--------|---------|');
    for (const m of metas) {
      lines.push(
        `| ${m.frontmatter.id} | ${m.frontmatter.title} | ${m.frontmatter.status} | ${m.frontmatter.updated} |`,
      );
    }
    lines.push('');
  }

  // SPEC sections grouped by release then layer
  const specs = sorted.filter((s) => s.frontmatter.id.startsWith('SPEC-'));
  const byRelease = groupBy(specs, (s) => s.frontmatter.release ?? 'unspecified');
  const releases = [...byRelease.keys()].sort();

  for (const release of releases) {
    const items = byRelease.get(release) ?? [];
    lines.push(`## ${release} Feature Specs (${items.length} total)`);
    lines.push('');

    const byLayer = groupBy(items, (s) => s.frontmatter.layer);
    const layers = [...byLayer.keys()].sort();

    for (const layer of layers) {
      const layerSpecs = byLayer.get(layer) ?? [];
      lines.push(`### ${layer}`);
      lines.push('');
      lines.push('| ID | Title | Status | Deps | Est LoC |');
      lines.push('|----|-------|--------|------|---------|');
      for (const s of layerSpecs) {
        const fm = s.frontmatter;
        const deps = fm.depends_on.length > 0 ? fm.depends_on.join(', ') : '—';
        lines.push(
          `| ${fm.id} | ${fm.title} | ${fm.status} | ${deps} | ${fm.estimated_loc} |`,
        );
      }
      lines.push('');
    }
  }

  // MOD section
  const mods = sorted.filter((s) => s.frontmatter.id.startsWith('MOD-'));
  if (mods.length > 0) {
    lines.push('## Module Overviews');
    lines.push('');
    lines.push('| ID | Title | Status |');
    lines.push('|----|-------|--------|');
    for (const m of mods) {
      lines.push(`| ${m.frontmatter.id} | ${m.frontmatter.title} | ${m.frontmatter.status} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function compareSpecs(a: ParsedSpec, b: ParsedSpec): number {
  return a.frontmatter.id.localeCompare(b.frontmatter.id);
}

function groupBy<T, K>(arr: T[], key: (t: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const item of arr) {
    const k = key(item);
    const list = m.get(k) ?? [];
    list.push(item);
    m.set(k, list);
  }
  return m;
}

function today(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/**
 * Atomically write index.md (temp file + rename).
 */
export async function writeIndex(indexPath: string, content: string): Promise<void> {
  const tmpPath = `${indexPath}.tmp.${process.pid}`;
  await Bun.write(tmpPath, content);
  // Bun doesn't have fs.rename; use node:fs
  const { rename } = await import('node:fs/promises');
  await rename(tmpPath, indexPath);
}

export type { SpecFrontmatter };
